package org.jphototagger.repository.sqlite;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Creates all database tables for SQLite.
 * Schema adapted from HSQLDB with SQLite-compatible syntax:
 * - BIGINT GENERATED BY DEFAULT AS IDENTITY -> INTEGER PRIMARY KEY AUTOINCREMENT
 * - VARCHAR_IGNORECASE -> TEXT COLLATE NOCASE
 * - VARBINARY -> BLOB
 * - CREATE CACHED TABLE -> CREATE TABLE
 */
public final class SqliteTables {

    private static final Logger LOGGER = Logger.getLogger(SqliteTables.class.getName());
    private final SqliteConnectionFactory connectionFactory;

    public SqliteTables(SqliteConnectionFactory connectionFactory) {
        this.connectionFactory = connectionFactory;
    }

    public void createTables() throws SQLException {
        try (Connection con = connectionFactory.getConnection();
             Statement stmt = con.createStatement()) {
            con.setAutoCommit(false);

            createApplicationTable(stmt);
            createFilesTable(stmt);
            create1nTables(stmt);
            createDcSubjectsTable(stmt);
            createXmpTable(stmt);
            createXmpDcSubjectTable(stmt);
            createExifTables(stmt);
            createCollectionsTables(stmt);
            createSavedSearchesTables(stmt);
            createAutoScanDirectoriesTable(stmt);
            createMetadataTemplateTable(stmt);
            createFavoriteDirectoriesTable(stmt);
            createFileExcludePatternsTable(stmt);
            createProgramsTable(stmt);
            createActionsAfterDbInsertionTable(stmt);
            createDefaultProgramsTable(stmt);
            createHierarchicalSubjectsTable(stmt);
            createSynonymsTable(stmt);
            createRenameTemplatesTable(stmt);
            createUserDefinedFileFiltersTable(stmt);
            createUserDefinedFileTypesTable(stmt);
            createWordsetTables(stmt);

            con.commit();
            LOGGER.info("SQLite database tables created successfully");
        }
    }

    private void createApplicationTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS application (
                key TEXT PRIMARY KEY,
                value BLOB
            )
            """);
    }

    private void createFilesTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS files (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                filename TEXT COLLATE NOCASE NOT NULL,
                size_in_bytes INTEGER,
                lastmodified INTEGER,
                xmp_lastmodified INTEGER
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_files ON files (filename)");
    }

    private void create1nTables(Statement stmt) throws SQLException {
        create1nTable(stmt, "dc_creators", "creator", 128);
        create1nTable(stmt, "dc_rights", "rights", 128);
        create1nTable(stmt, "iptc4xmpcore_locations", "location", 64);
        create1nTable(stmt, "photoshop_authorspositions", "authorsposition", 32);
        create1nTable(stmt, "photoshop_captionwriters", "captionwriter", 32);
        create1nTable(stmt, "photoshop_cities", "city", 32);
        create1nTable(stmt, "photoshop_countries", "country", 64);
        create1nTable(stmt, "photoshop_credits", "credit", 32);
        create1nTable(stmt, "photoshop_sources", "source", 32);
        create1nTable(stmt, "photoshop_states", "state", 32);
    }

    private void create1nTable(Statement stmt, String tablename, String columnname, int length)
            throws SQLException {
        stmt.execute(String.format("""
            CREATE TABLE IF NOT EXISTS %s (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                %s TEXT COLLATE NOCASE
            )
            """, tablename, columnname));
        stmt.execute(String.format(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_%s_id ON %s (id)", tablename, tablename));
        stmt.execute(String.format(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_%s_%s ON %s (%s)",
            tablename, columnname, tablename, columnname));
    }

    private void createDcSubjectsTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS dc_subjects (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                subject TEXT COLLATE NOCASE
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_dc_subjects_id ON dc_subjects (id)");
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_dc_subjects_subject ON dc_subjects (subject)");
    }

    private void createXmpTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS xmp (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                id_file INTEGER NOT NULL,
                id_dc_creator INTEGER,
                dc_description TEXT COLLATE NOCASE,
                id_dc_rights INTEGER,
                dc_title TEXT COLLATE NOCASE,
                id_iptc4xmpcore_location INTEGER,
                id_photoshop_authorsposition INTEGER,
                id_photoshop_captionwriter INTEGER,
                id_photoshop_city INTEGER,
                id_photoshop_country INTEGER,
                id_photoshop_credit INTEGER,
                photoshop_headline TEXT COLLATE NOCASE,
                photoshop_instructions TEXT COLLATE NOCASE,
                id_photoshop_source INTEGER,
                id_photoshop_state INTEGER,
                photoshop_transmissionReference TEXT COLLATE NOCASE,
                rating INTEGER,
                iptc4xmpcore_datecreated TEXT COLLATE NOCASE,
                FOREIGN KEY (id_file) REFERENCES files (id) ON DELETE CASCADE,
                FOREIGN KEY (id_dc_creator) REFERENCES dc_creators (id) ON DELETE SET NULL,
                FOREIGN KEY (id_dc_rights) REFERENCES dc_rights (id) ON DELETE SET NULL,
                FOREIGN KEY (id_iptc4xmpcore_location) REFERENCES iptc4xmpcore_locations (id) ON DELETE SET NULL,
                FOREIGN KEY (id_photoshop_authorsposition) REFERENCES photoshop_authorspositions (id) ON DELETE SET NULL,
                FOREIGN KEY (id_photoshop_captionwriter) REFERENCES photoshop_captionwriters (id) ON DELETE SET NULL,
                FOREIGN KEY (id_photoshop_city) REFERENCES photoshop_cities (id) ON DELETE SET NULL,
                FOREIGN KEY (id_photoshop_country) REFERENCES photoshop_countries (id) ON DELETE SET NULL,
                FOREIGN KEY (id_photoshop_credit) REFERENCES photoshop_credits (id) ON DELETE SET NULL,
                FOREIGN KEY (id_photoshop_source) REFERENCES photoshop_sources (id) ON DELETE SET NULL,
                FOREIGN KEY (id_photoshop_state) REFERENCES photoshop_states (id) ON DELETE SET NULL
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_xmp_id_files ON xmp (id_file)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_xmp_dc_description ON xmp (dc_description)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_xmp_dc_title ON xmp (dc_title)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_xmp_photoshop_headline ON xmp (photoshop_headline)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_xmp_iptc4xmpcore_datecreated ON xmp (iptc4xmpcore_datecreated)");
    }

    private void createXmpDcSubjectTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS xmp_dc_subject (
                id_xmp INTEGER,
                id_dc_subject INTEGER,
                PRIMARY KEY (id_xmp, id_dc_subject),
                FOREIGN KEY (id_xmp) REFERENCES xmp (id) ON DELETE CASCADE,
                FOREIGN KEY (id_dc_subject) REFERENCES dc_subjects (id) ON DELETE CASCADE
            )
            """);
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_xmp_dc_subject_id_xmp ON xmp_dc_subject (id_xmp)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_xmp_dc_subject_id_dc_subject ON xmp_dc_subject (id_dc_subject)");
    }

    private void createExifTables(Statement stmt) throws SQLException {
        create1nTable(stmt, "exif_recording_equipment", "equipment", 125);
        create1nTable(stmt, "exif_lenses", "lens", 256);

        stmt.execute("""
            CREATE TABLE IF NOT EXISTS exif (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                id_file INTEGER NOT NULL,
                id_exif_recording_equipment INTEGER,
                exif_date_time_original TEXT,
                exif_focal_length REAL,
                exif_iso_speed_ratings INTEGER,
                id_exif_lens INTEGER,
                exif_date_time_original_timestamp INTEGER,
                exif_gps_latitude REAL,
                exif_gps_longitude REAL,
                FOREIGN KEY (id_file) REFERENCES files (id) ON DELETE CASCADE,
                FOREIGN KEY (id_exif_recording_equipment) REFERENCES exif_recording_equipment (id) ON DELETE SET NULL,
                FOREIGN KEY (id_exif_lens) REFERENCES exif_lenses (id) ON DELETE SET NULL
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_exif_id_files ON exif (id_file)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_exif_date_time_original ON exif (exif_date_time_original)");
    }

    private void createCollectionsTables(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS collection_names (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT COLLATE NOCASE
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_collection_names_id ON collection_names (id)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_collection_names_name ON collection_names (name)");

        stmt.execute("""
            CREATE TABLE IF NOT EXISTS collections (
                id_collectionnname INTEGER,
                id_file INTEGER,
                sequence_number INTEGER,
                FOREIGN KEY (id_collectionnname) REFERENCES collection_names (id) ON DELETE CASCADE,
                FOREIGN KEY (id_file) REFERENCES files (id) ON DELETE CASCADE
            )
            """);
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_collections_id_collectionnnames ON collections (id_collectionnname)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_collections_id_files ON collections (id_file)");
    }

    private void createSavedSearchesTables(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS saved_searches (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT COLLATE NOCASE,
                custom_sql BLOB,
                search_type INTEGER
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_saved_searches_name ON saved_searches (name)");

        stmt.execute("""
            CREATE TABLE IF NOT EXISTS saved_searches_panels (
                id_saved_search INTEGER,
                panel_index INTEGER,
                bracket_left_1 INTEGER,
                operator_id INTEGER,
                bracket_left_2 INTEGER,
                column_id INTEGER,
                comparator_id INTEGER,
                value TEXT,
                bracket_right INTEGER,
                FOREIGN KEY (id_saved_search) REFERENCES saved_searches (id) ON DELETE CASCADE
            )
            """);

        stmt.execute("""
            CREATE TABLE IF NOT EXISTS saved_searches_keywords (
                id_saved_search INTEGER,
                keyword TEXT COLLATE NOCASE,
                FOREIGN KEY (id_saved_search) REFERENCES saved_searches (id) ON DELETE CASCADE
            )
            """);
    }

    private void createAutoScanDirectoriesTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS autoscan_directories (
                directory TEXT COLLATE NOCASE
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_autoscan_directories_directory ON autoscan_directories (directory)");
    }

    private void createMetadataTemplateTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS metadata_edit_templates (
                name TEXT COLLATE NOCASE,
                dcSubjects BLOB,
                dcTitle BLOB,
                photoshopHeadline BLOB,
                dcDescription BLOB,
                photoshopCaptionwriter BLOB,
                iptc4xmpcoreLocation BLOB,
                dcRights BLOB,
                dcCreator BLOB,
                photoshopAuthorsposition BLOB,
                photoshopCity BLOB,
                photoshopState BLOB,
                photoshopCountry BLOB,
                photoshopTransmissionReference BLOB,
                photoshopInstructions BLOB,
                photoshopCredit BLOB,
                photoshopSource BLOB,
                rating BLOB,
                iptc4xmpcore_datecreated BLOB
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_metadata_edit_templates_name ON metadata_edit_templates (name)");
    }

    private void createFavoriteDirectoriesTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS favorite_directories (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                favorite_name TEXT COLLATE NOCASE,
                directory_name TEXT,
                favorite_index INTEGER
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_favorite_directories_favorite_name ON favorite_directories (favorite_name)");
    }

    private void createFileExcludePatternsTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS file_exclude_patterns (
                pattern TEXT COLLATE NOCASE
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_file_exclude_pattern_pattern ON file_exclude_patterns (pattern)");
    }

    private void createProgramsTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS programs (
                id INTEGER NOT NULL,
                action INTEGER,
                filename TEXT NOT NULL,
                alias TEXT COLLATE NOCASE NOT NULL,
                parameters_before_filename BLOB,
                parameters_after_filename BLOB,
                input_before_execute INTEGER,
                input_before_execute_per_file INTEGER,
                single_file_processing INTEGER,
                change_file INTEGER,
                sequence_number INTEGER,
                use_pattern INTEGER,
                pattern BLOB
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_programs_id ON programs (id)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_programs_alias ON programs (alias)");
    }

    private void createActionsAfterDbInsertionTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS actions_after_db_insertion (
                id_program INTEGER NOT NULL,
                action_order INTEGER
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_actions_after_db_insertion_id_programs ON actions_after_db_insertion (id_program)");
    }

    private void createDefaultProgramsTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS default_programs (
                id_program INTEGER NOT NULL,
                filename_suffix TEXT COLLATE NOCASE
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_default_programs_filename_suffix ON default_programs (filename_suffix)");
    }

    private void createHierarchicalSubjectsTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS hierarchical_subjects (
                id INTEGER NOT NULL,
                id_parent INTEGER,
                subject TEXT COLLATE NOCASE NOT NULL,
                real INTEGER
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_hierarchical_subjects_id ON hierarchical_subjects (id)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_hierarchical_subjects_subject ON hierarchical_subjects (subject)");
    }

    private void createSynonymsTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS synonyms (
                word TEXT,
                synonym TEXT,
                PRIMARY KEY (word, synonym)
            )
            """);
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_synonyms_word ON synonyms (word)");
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_synonyms_synonym ON synonyms (synonym)");
    }

    private void createRenameTemplatesTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS rename_templates (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                start_number INTEGER,
                step_width INTEGER,
                number_count INTEGER,
                date_delimiter TEXT,
                format_class_at_begin TEXT,
                delimiter_1 TEXT,
                format_class_in_the_middle TEXT,
                delimiter_2 TEXT,
                format_class_at_end TEXT,
                text_at_begin TEXT,
                text_in_the_middle TEXT,
                text_at_end TEXT,
                UNIQUE(name)
            )
            """);
    }

    private void createUserDefinedFileFiltersTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS user_defined_file_filters (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                is_not INTEGER,
                type INTEGER,
                name TEXT COLLATE NOCASE NOT NULL,
                expression TEXT NOT NULL,
                UNIQUE(name)
            )
            """);
    }

    private void createUserDefinedFileTypesTable(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS user_defined_file_types (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                suffix TEXT COLLATE NOCASE NOT NULL,
                description TEXT COLLATE NOCASE,
                external_thumbnail_creator INTEGER
            )
            """);
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_user_defined_file_types_suffix ON user_defined_file_types (suffix)");
    }

    private void createWordsetTables(Statement stmt) throws SQLException {
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS wordsets (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT COLLATE NOCASE
            )
            """);
        stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_wordsets_name ON wordsets (name)");

        stmt.execute("""
            CREATE TABLE IF NOT EXISTS wordsets_words (
                id_wordsets INTEGER,
                word TEXT COLLATE NOCASE,
                word_order INTEGER,
                FOREIGN KEY (id_wordsets) REFERENCES wordsets (id) ON DELETE CASCADE
            )
            """);
        stmt.execute("CREATE INDEX IF NOT EXISTS idx_wordsets_words_id_wordsets ON wordsets_words (id_wordsets)");
    }
}
