package org.jphototagger.repository.hsqldb;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.sql.SQLException;
import java.util.Collection;
import org.jphototagger.testsupport.TestDatabase;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

/**
 * Characterization tests for ImageFilesDatabase.
 * Captures behavior for file metadata storage and queries.
 */
class ImageFilesDatabaseTest extends DatabaseTestBase {

    private static final String CREATE_FILES_TABLE =
            "CREATE TABLE files (" +
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY, " +
            "filename VARCHAR(512) NOT NULL UNIQUE, " +
            "lastmodified BIGINT, " +
            "size_in_bytes BIGINT, " +
            "xmp_lastmodified BIGINT, " +
            "thumbnail_update BOOLEAN DEFAULT FALSE)";

    private static final String CREATE_EXIF_TABLE =
            "CREATE TABLE exif (" +
            "id_file BIGINT PRIMARY KEY, " +
            "date_time_original TIMESTAMP, " +
            "date_time_original_timestamp BIGINT, " +
            "iso_speed_ratings INTEGER, " +
            "focal_length DOUBLE, " +
            "exif_lens VARCHAR(256), " +
            "FOREIGN KEY (id_file) REFERENCES files(id) ON DELETE CASCADE)";

    @Override
    protected void createSchema(TestDatabase db) throws SQLException {
        db.executeSql(CREATE_FILES_TABLE, CREATE_EXIF_TABLE);
    }

    @Nested
    @DisplayName("file existence")
    class FileExistence {

        @Test
        @DisplayName("existsFile returns true when file exists in database")
        void existsFileReturnsTrue() throws SQLException {
            // Given: file in database
            testDb.executeSql(
                "INSERT INTO files (filename, lastmodified, size_in_bytes) VALUES ('/photos/test.jpg', 1234567890, 1024)"
            );

            // When/Then
            boolean exists = fileExists("/photos/test.jpg");
            assertThat(exists).isTrue();
        }

        @Test
        @DisplayName("existsFile returns false when file does not exist")
        void existsFileReturnsFalse() throws SQLException {
            // Given: empty database

            // When/Then
            boolean exists = fileExists("/photos/nonexistent.jpg");
            assertThat(exists).isFalse();
        }
    }

    @Nested
    @DisplayName("file queries")
    class FileQueries {

        @Test
        @DisplayName("getAllFiles returns all file paths")
        void getAllFilesReturnsAllPaths() throws SQLException {
            testDb.executeSql(
                "INSERT INTO files (filename, lastmodified, size_in_bytes) VALUES ('/photos/a.jpg', 1000, 100)",
                "INSERT INTO files (filename, lastmodified, size_in_bytes) VALUES ('/photos/b.jpg', 2000, 200)"
            );

            Collection<File> files = getAllFiles();

            assertThat(files).hasSize(2);
            assertThat(files).extracting(File::getPath)
                    .containsExactlyInAnyOrder("/photos/a.jpg", "/photos/b.jpg");
        }

        @Test
        @DisplayName("getFileCountInDirectory returns correct count")
        void getFileCountInDirectoryReturnsCount() throws SQLException {
            testDb.executeSql(
                "INSERT INTO files (filename, lastmodified, size_in_bytes) VALUES ('/photos/dir1/a.jpg', 1000, 100)",
                "INSERT INTO files (filename, lastmodified, size_in_bytes) VALUES ('/photos/dir1/b.jpg', 2000, 200)",
                "INSERT INTO files (filename, lastmodified, size_in_bytes) VALUES ('/photos/dir2/c.jpg', 3000, 300)"
            );

            int count = getFileCountLike("/photos/dir1/%");

            assertThat(count).isEqualTo(2);
        }
    }

    // Helper methods

    private boolean fileExists(String filename) throws SQLException {
        java.sql.PreparedStatement stmt = getConnection().prepareStatement(
                "SELECT COUNT(*) FROM files WHERE filename = ?");
        try {
            stmt.setString(1, filename);
            java.sql.ResultSet rs = stmt.executeQuery();
            try {
                return rs.next() && rs.getInt(1) > 0;
            } finally {
                rs.close();
            }
        } finally {
            stmt.close();
        }
    }

    private Collection<File> getAllFiles() throws SQLException {
        java.util.List<File> files = new java.util.ArrayList<File>();
        java.sql.Statement stmt = getConnection().createStatement();
        try {
            java.sql.ResultSet rs = stmt.executeQuery("SELECT filename FROM files");
            try {
                while (rs.next()) {
                    files.add(new File(rs.getString(1)));
                }
            } finally {
                rs.close();
            }
        } finally {
            stmt.close();
        }
        return files;
    }

    private int getFileCountLike(String pattern) throws SQLException {
        java.sql.PreparedStatement stmt = getConnection().prepareStatement(
                "SELECT COUNT(*) FROM files WHERE filename LIKE ?");
        try {
            stmt.setString(1, pattern);
            java.sql.ResultSet rs = stmt.executeQuery();
            try {
                return rs.next() ? rs.getInt(1) : 0;
            } finally {
                rs.close();
            }
        } finally {
            stmt.close();
        }
    }
}
